### PR TITLE
Implement Windows retrying as administrator to update PHP ini

### PR DESCRIPTION
**Pull request by stevebauman**
This PR implements the Windows retrying as an administrator functionality as seen in the video below:

Let me know if you'd like any adjustments or changes to anything, thanks! 🙏 

https://user-images.githubusercontent.com/6421846/156000838-0024e348-3957-45c1-9e3c-741ea7948462.mov

### CODE REVIEW

**Comment by stevebauman** [comment]
This seems to be related to our issue with having two composer autoloaders via `ray()`and `dd()` phars:

https://github.com/humbug/php-scoper/blob/master/docs/limitations.md#composer-autoloader

https://github.com/humbug/php-scoper/issues/298#issuecomment-525700081

**Comment by stevebauman** [comment]
Ooof, this is going to be super tricky to get up and running with `dd()` and `ray()` being two different phars. We'll have to somehow hijack scopers autoload generation, or generate the phars in two separate processes so the composer autoloaders have different class names.

**Comment by freekmurze** [comment]
> Ooof, this is going to be super tricky to get up and running with dd() and ray() being two different phars. We'll have to somehow hijack scopers autoload generation, or generate the phars in two separate processes so the composer autoloaders have different class names.

Maybe we could split `build` into two commands (`build-ray` and `build-dump`) and use two separate workflows. 
Would that solve the issue?

**Comment by stevebauman** [comment]
Bah! It was the requirements checker. It was storing it's composer autoload into the phar. Took a while 😅 

We're all green @freekmurze!

**Comment by freekmurze** [comment]
Very cool, thanks for having gone the extra mile here. 👍 

 I usually don't care too much about Windows users 😬

**Comment by stevebauman** [comment]
Happy to help! And haha we can't forget about them Freek! 😄

**Pull request merged**
